CREATE DATABASE AGENDA
USE AGENDA

CREATE TABLE PATIENT(
	idPaciente BIGINT IDENTITY(1,1) PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	horario VARCHAR(5) NOT NULL,
	procedimento VARCHAR(500) NOT NULL,
	dia VARCHAR(10) NOT NULL
)

INSERT INTO PATIENT (NAME_PATIENT,TIME_SCHDL,PROCESS,DATE_SCHDL)
VALUES('SAMUEL','16:00','MASSAGEM','10/10/2023')

SELECT * FROM PATIENT



drop table PATIENT

